### ISSUE TITLE
FiercePhish dont start

### ISSUE THREAD

**Issue by dnkls** [Raikia/FiercePhish#40] opened 2017-04-10 08:35 UTC
I use auto install method , all installation run perfect:

http://i.imgur.com/flKUzSd.png

...but admin panel dont start:

http://i.imgur.com/yXH5J2q.png

**Comment by Raikia** [comment] 2017-04-10 14:08
It looks like PHP wasn't installed properly...?

Try running ```./install.sh -v | tee log.txt```.  If it still doesn't work, send me log.txt.

**Comment by Raikia** [comment] 2017-05-04 07:49
Closed as probably duplicate of #35

**Closed by Raikia** 2017-05-04 07:49 UTC
Labels: duplicate, more info needed
