### ISSUE TITLE
Issue with the progress bar

### ISSUE THREAD

**Issue by AbdullahAsem** [Raikia/FiercePhish#34] opened 2017-02-08 18:50 UTC
there is a java script issue happens during uploading csv file for targets, the progress bar freez the navigation and everything else, same issue with DateJS, any solutions ?

**Comment by Raikia** [comment] 2017-02-08 19:03
I haven't run into this problem, even when uploading a target file with over 150,000 users in it.  What browser are you using? What version of FiercePhish (is it the latest version?).

    same issue with DateJS

What do you mean by this? 

When you upload a target file, it should start a background job that processes the uploaded file:

![img](https://vgy.me/GVFUbz.png)

Are you saying that this UI freezes your browser?  Does it unfreeze after the process is completed?  Also please [attach logs as it may help](https://github.com/Raikia/FiercePhish/wiki/Reporting-Bugs)

**Comment by AbdullahAsem** [comment] 2017-02-08 20:02
Well, its upload progress is not working, and I am getting the following error, moreover the navigation is not working at all 
![00228](https://cloud.githubusercontent.com/assets/4209603/22755050/8c4f2ae6-ee0f-11e6-8687-f084b10c55a2.PNG)
![000258](https://cloud.githubusercontent.com/assets/4209603/22755051/8c4ff976-ee0f-11e6-8ae1-a7c6d0928568.PNG)

**Comment by Raikia** [comment] 2017-02-08 20:39
The issue is already fixed here: #33 .  Read that for a solution.

That said, v1.2.0 is now released and I recommend switching to that, as all these issues are resolved in it.  v1.2.0. will require a reinstall.  [Instructions here](https://github.com/Raikia/FiercePhish/wiki/Upgrade-Instructions#uninstall-fiercephish)

**Comment by AbdullahAsem** [comment] 2017-02-08 21:51
The issue got resolved! thank you for the quick responses :+1:

**Closed** 2017-02-08 22:03 UTC
Labels: invalid
